const remoteCompanies = [
  {
    name: "Librato",
    body: "Cloud Monitoring.",
    url: "http://solarwinds.jobs/solarwinds-cloud/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Linaro",
    body: "OpenSource Engineering on ARM.",
    url: "https://www.linaro.org/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Lincoln Loop",
    body: "WebDev shop.",
    url: "https://lincolnloop.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Litmus",
    body: "Optimization tools for email professionals. Offices in Boston and London, but nearly 50% of the team works remotely.",
    url: "https://litmus.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "LivingSocial",
    body: "Company-wide support for teams of experienced, remote developers. Lots of autonomy.",
    url: "https://jobs.groupon.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Lullabot",
    body: "Strategy, design and development using Drupal.",
    url: "https://www.lullabot.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "madewithlove",
    body: "We help companies build digital products and bring new juice to teams that seem to jam.",
    url: "https://madewithlove.be/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Maintainer Mountaineer",
    body: "Open source community management as a service.",
    url: "https://maintainer.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MariaDB",
    body: "Open source database.",
    url: "https://mariadb.com/about-us/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MarsBased",
    body: "MarsBased is a development consultancy from Barcelona offering end‑to‑end web & mobile apps based on Ruby on Rails, Angular and other Javascript frameworks.",
    url: "https://marsbased.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mapbox",
    body: "Map integration tools for various platforms.",
    url: "https://www.mapbox.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MCFTech",
    body: "Applications to help you run your business succesfully.",
    url: "https://www.mcftech.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MeetEdgar",
    body: "Automated social sharing. US remote.",
    url: "https://meetedgar.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mobile Jazz",
    body: "We are a dedicated team of highly-skilled engineers, designers and marketing experts on a mission to build a more beautiful digital world. We are a remote friendly company with headquarters in Barcelona.",
    url: "https://mobilejazz.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Modern Tribe",
    body: "A digital agency with a modern twist. All freelancers. All experts.",
    url: "http://tri.be/about/join-our-team/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Modus Create",
    body: "Modus is a digital design-build agency driven by world-class talent. PHP, Javascript.",
    url: "https://moduscreate.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mosalingua",
    body: "Learn words, enjoy the world.",
    url: "https://www.mosalingua.com/en/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MVP Space",
    body: "Test a business idea with your target audience or show its potential to your investors.",
    url: "http://mvp-space.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mozilla",
    body: "Firefox has a 'Remote' option under it's location searchbar.",
    url: "https://careers.mozilla.org/listings/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "NearForm",
    body: "NearForm evolves enterprises by building high-performance, open software. Our global team uses modern processes and tools to help clients innovate at speed.",
    url: "https://www.nearform.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Nectafy",
    body: "nbound marketing and content creation.",
    url: "http://nectafy.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Netsparker",
    body: "Web Application Security Scanner.",
    url: "https://www.netsparker.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Next Big Sound",
    body: "Analytics and Insights for the Music Industry.",
    url: "https://www.nextbigsound.com/about",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "NinjaCat",
    body: "Reporting, Monitoring & Call Tracking Platform for Leading Digital Agencies.",
    url: "https://www.ninjacat.io/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Niteo",
    body: "A decade old SaaS studio full of bright ideas, building smart solutions to empower small businesses online.",
    url: "https://niteo.co/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "NodeSource",
    body: "NodeSource is dedicated to creating a sustainable ecosystem for Node.js.",
    url: "https://nodesource.com/about",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ofri",
    body: "A swiss online marketplace that connects homeowners with quality home improvement professionals.",
    url: "https://www.ofri.ch/job_openings",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Olark",
    body: "Chat support funnel.",
    url: "https://www.olark.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "onTheGo Systems",
    body: "WordPress Developer, Supporter and Marketing Jobs.",
    url: "https://www.onthegosystems.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Onyo",
    body: "Transforming the eating out experience in pure pleasure.",
    url: "http://www.onyo.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "OpenCraft",
    body: "Open edX development (Free Software MOOC project).",
    url: "http://opencraft.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Owsy",
    body: "International studio focused on creating products for financial service firms.",
    url: "http://owsy.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Parknav",
    body: "Intelligent parking using AI.",
    url: "https://parknav.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Parsely",
    body: "Analytics solutions.",
    url: "http://www.parsely.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Particular Software (NServiceBus)",
    body: "Enterprise Service Bus, Messaging, C#, Open Source.",
    url: "https://particular.net/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Patients Know Best",
    body: "Empowering patients to manage their care, enabling professionals to share information while improving efficiencies for payers.",
    url: "https://patients.workable.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Paylocity",
    body: "HR and payroll solutions.",
    url: "http://www.paylocity.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Pilot",
    body: "Pilot is a software platform that removes all the pain from contract work. We find work, negotiate contracts, send invoices and chase payments for hundreds of forward-looking engineers and designers around the world.",
    url: "https://pilot.co/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Pleo",
    body: "Pleo is a company payment card solution that automates expense reports and simplifies company spending.",
    url: "https://careers.pleo.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Precision Nutrition",
    body: "Online Nutrition Coaching and Certification.",
    url: "http://www.precisionnutrition.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "PreviousNext",
    body: "Australian based Drupal agency.",
    url: "https://www.previousnext.com.au/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Prezly",
    body: "SaaS PR platform. PHP, React, JS, Postgres. 100% remote.",
    url: "https://www.prezly.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "RainforestQA",
    body: " On demand QA as a service.",
    url: "https://www.rainforestqa.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Reaction Commerce",
    body: "Fastest-growing open source ecommerce platform. Node.js, MongoDB, Kubernetes, Docker.",
    url: "https://reactioncommerce.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Real HQ",
    body: "Maker of Agent Pronto, software designed to help make home buying and selling a better experience. We've been remote since the start, now 50+ spread across the globe. Ruby, Rails, React.js, iOS/Android.",
    url: "https://realhq.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "RebelMouse",
    body: "Social publishing platform. Python, JS & iOS/Android developers. All over the world team.",
    url: "https://blog.rebelmouse.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Recurly",
    body: "recurring billing management for subscription-based businesses.",
    url: "https://recurly.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Red Hat.",
    body: "",
    url: "http://jobs.redhat.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "RightScale.",
    body: "",
    url: "http://www.rightscale.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Sangoma",
    body: "Trusted leader in delivering globally scalable Voice-Over-IP telephony systems, both on-site and cloud-based. C, PHP, Python, JavaScript, Linux, FreePBX, VoIP.",
    url: "http://www.sangoma.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Scrapinghub",
    body: "",
    url: "https://scrapinghub.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ServiceNow",
    body: "Enterprise cloud computing to improve service levels, energize employees, and change the way your enterprise works. Work at lightspeed.",
    url: "http://jobs.jobvite.com/servicenow/search?c=&l=&r=&t=&q=remote",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ShakaCode",
    body: "A global web development software consultancy and product company.",
    url: "http://www.shakacode.com/about/index.html#work-with-us",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Shogun",
    body: "Build and optimize eCommerce landing pages. Ruby / Rails, Go, JavaScript, React. 100% remote.",
    url: "https://getshogun.com/team",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Signal",
    body: "These people make the fantastic Signal app. US Only.",
    url: "https://www.signal.org/workworkwork/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Simple",
    body: "",
    url: "https://www.simple.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Skyscrapers",
    body: "Cloud hosting services & management. Working with multiple cloud providers (AWS, Digital Ocean, Linode, ...). 100% remote.",
    url: "http://skyscrapers.eu/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "SoftwareMill",
    body: "",
    url: "https://softwaremill.com/join-us/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Soshace",
    body: "Angular/React/Vue.js/Java/Python remote development company. ",
    url: "https://soshace.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Songspace",
    body: "Helps music creators collaborate, catalog, and share work with their professional team.",
    url: "https://songspace.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Soostone",
    body: "",
    url: "http://www.soostone.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Splice Machine",
    body: "Combines the functionality of a relational database, data warehouse, and machine learning in one unified AI platform.",
    url: "https://www.splicemachine.com/company/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Spreaker",
    body: "Discover and listen to your favorite podcasts.",
    url: "https://www.spreaker.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "StackExchange.",
    body: "",
    url: "http://stackexchange.com/work-here",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Strongloop",
    body: "",
    url: "https://strongloop.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Student Loan Hero",
    body: "100% remote company on a mission to help 44 million Americans manage and repay over $1.4 trillion in student loan.",
    url: "https://studentloanhero.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "StyleSeat",
    body: "we love high-impact remote engineers, collaboration, creativity, python, angularjs.",
    url: "http://static.styleseat.com/jobs/index.html",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Surevine",
    body: "",
    url: "https://www.surevine.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Surge",
    body: "100% remote consulting company working primarily in Node.JS, iOS, .NET, PHP, and Android.",
    url: "http://www.surgeforward.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Sysdig Cloud",
    body: "",
    url: "https://sysdig.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Taskade",
    body: "Remote team building real-time collaboration & collaborative editing for teams.",
    url: "https://www.taskade.com/contact/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "TaxJar",
    body: "Eliminate sales tax headaches.",
    url: "https://www.taxjar.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Teamed.io",
    body: "",
    url: "http://teamed.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "TeamSnap",
    body: "TeamSnap is the No. 1 online sports team management software. 80% remote employees.",
    url: "https://www.teamsnap.com/about/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
];

export default remoteCompanies;
