const remoteCompanies = [
  {
    name: "Chili Piper",
    body: "100% fully remote team, with good benefits.",
    url: "https://www.chilipiper.com/careers/",
    hq: null,
    remoteModel: "full",
    timezone: null,
  },
  {
    name: "Valohai",
    body: "Machine Learning version control in the cloud",
    url: "https://valohai.com/careers/",
    hq: "Finland",
    remoteModel: null,
    timezone: "UTC+2",
  },
  {
    name: "10up",
    body: "10up makes the web better by finely crafting websites & tools for content creators.",
    url: "https://10up.com/careers/",
    hq: "United States",
    remoteModel: "full",
    timezone: null,
  },
  {
    name: "Aha!",
    body: "Aha! is roadmapping software for PMs who want their mojo back.",
    url: "https://www.aha.io/company/careers/current-openings",
    hq: "United States",
    remoteModel: "full",
    timezone: "UTC-6",
  },
  {
    name: "Alley",
    body: "Digital Agency. We are strategists, researchers, designers, and developers who craft custom digital experiences for publishers, nonprofit institutions, museums, and brands.",
    url: "https://alley.co/jobs/",
    hq: "United States",
    remoteModel: "full",
    timezone: null,
  },
  {
    name: "ALICE",
    body: "Remote-friendly start-up company. We’re creating the global operations platform for the hospitality industry. ALICE empowers the world's best hotels to deliver a remarkable guest experience. ",
    url: "https://www.aliceplatform.com/careers/",
    hq: "United States",
    remoteModel: "hybrid",
    timezone: null,
  },
  {
    name: "Arkency",
    body: "Rails and React.js experts, fully remote/async. ",
    url: "https://arkency.com/join-our-team/",
    hq: null,
    remoteModel: "full",
    timezone: null,
  },
  {
    name: "Articulate",
    body: "EdTech. Makes software that helps teachers make e-learning courses. Ruby, Node, C#, and .NET for Windows app. ",
    url: "https://articulate.com/about/careers",
    hq: "United States",
    remoteModel: "full",
    timezone: "UTC-6",
  },
  {
    name: "Okta",
    body: "Zero-friction authentication and authorization for developers. ",
    url: "https://www.okta.com/company/careers/",
    hq: "United States",
    remoteModel: "hybrid",
    timezone: null,
  },
  {
    name: "Authentic F & F",
    body: "Independent design and technology studio based in Denver and Minnesota.",
    url: "https://authenticff.com/careers",
    hq: "United States",
    remoteModel: "full",
    timezone: "UTC-6",
  },
  {
    name: "Aurity",
    body: "100% remote company, specializing in React and React Native.",
    url: "https://aurity.co/join-us",
    hq: "United Kingdom",
    remoteModel: "full",
    timezone: null,
  },
  {
    name: "Automattic",
    body: "Makers of WordPress.com and Gravatar.",
    url: "https://automattic.com/work-with-us/",
    hq: null,
    remoteModel: "full",
    timezone: null,
  },
  {
    name: "AvantStay",
    body: "Short-term rental company based in Los Angeles, with remote dev team.",
    url: "https://avantstay.com/careers",
    hq: "United States",
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Axelerant",
    body: "",
    url: "https://www.axelerant.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Baremetrics",
    body: "Analytics and insights for Stripe, Braintree, Recurly and Chargify.",
    url: "https://baremetrics.com/about",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "BaseCamp",
    body: "Project management software.",
    url: "http://basecamp.com/about/team",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Baselayer",
    body: "Data center and infrastructure management software.",
    url: "https://www.baselayer.com/company/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Basho",
    body: "Creators of Riak, an open source platform and k/v database. We code in Erlang and hang out on clouds. Everyone works remote and gets together a few times a year at HQ in Seattle.",
    url: "http://basho.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "BeBanjo",
    body: "Software as a service for managing video on-demand. Ruby / Rails, Elasticsearch, Sidekiq.",
    url: "http://bebanjo.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Bluespark Labs",
    body: "WebDev Consulting and makers of Roomify. Remote team with HQs in Raleigh, NC and Italy. Drupal.",
    url: "http://www.bluespark.com/work-at-bluespark",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "BookingSync",
    body: "Vacation Rental Software for professionals. Fully distributed team, we work remotely and try to make a company retreat each year. Proud Ember.js official sponsor, Ruby / Rails.",
    url: "https://www.bookingsync.com/en/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Brave",
    body: "Web browser with built-in ad blocker and crypto-token micro-payments.",
    url: "https://brave.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Buffer",
    body: "Tools to help manage social media. PHP, CodeIgniter, MongoDB, Memcache, Backbone.js, React.js, Grunt.js, LESS, and Python.",
    url: "https://buffer.com/journey/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Bugfender",
    body: "Bugfender is a remote logger for multiple platforms including iOS and Android. It stores logs created by your application and sends them to our server, creating a remote console where you can see logs in real time. Remote company based in Barcelona.",
    url: "https://bugfender.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ButterCloud",
    body: "A small team of web & app developers. We help startups & small to medium sized businesses build, maintain, and grow their products.",
    url: "http://www.buttercloud.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Cadasta",
    body: "Secure platform for mapping global land & resource rights. 100% remote team; Python, Django, JavaScript, PostgreSQL.",
    url: "http://cadasta.org/about-us/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Canonical",
    body: "The makers of the Linus distribution Ubuntu.",
    url: "https://www.canonical.com/careers/all-vacancies",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Catalyze",
    body: "HIPAA-compliant cloud computing for healthcare. HQ in Madison, WI. Docker, Go, Python.",
    url: "https://catalyze.io/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Chef",
    body: "We are all about IT automation for speed and awesomeness. Ruby, JavaScript & shell scripting. HQ in Seattle but we have employees all around US.",
    url: "https://www.chef.io/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Ciao Bambino",
    body: "Family destinations and hotel reviews.",
    url: "http://ciaobambino.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "CircleCI",
    body: "Provides continuous integration tools and services.",
    url: "https://circleci.com/jobs#engineer",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Circonus",
    body: "SaaS and on-prem monitoring, analytics, alerting, and more. C, Go, Java, Perl. HQ in Fulton MD, most employees are remote.",
    url: "https://www.circonus.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Clevertech",
    body: "We build incredible, game changing technology. ",
    url: "https://clevertech.biz/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Close.io",
    body: "Inside sales CRM for startups and SMBs.",
    url: "http://close.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Codeship",
    body: "SaaS Continuous Delivery.",
    url: "https://codeship.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Collabora",
    body: "Open source software-based consulting.",
    url: "https://www.collabora.com/careers.html",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Collage",
    body: "We provide the easiest and most versatile tools to help you turn your photos into memories. 100% remote team.",
    url: "http://jobs.collage.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Compose",
    body: "Managing databases as a service. Distributed team with offices in San Meteo, CA and Birmingham, AL. ",
    url: "https://www.compose.io/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ConsenSys",
    body: "Blockchain software technology company with offices all around the world, and independent employees in even more locations.",
    url: "https://consensys.net/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Continu",
    body: "Continuous learning software for modern teams.",
    url: "http://www.continu.co/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Countly",
    body: "Open source, enterprise mobile / web analytics and marketing platform.",
    url: "https://count.ly/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "CRO Metrics",
    body: "Data-driven expirementation and growth programs.",
    url: "http://crometrics.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Crossover",
    body: "Project-based Java, .Net and DevOps positions.",
    url: "https://app.crossover.com/x/marketplace/available-jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Datadog",
    body: "Easy to use and scalable monitoring systems for modern and dynamic infrastructure. Distributed team with offices in New York, Boston and Paris. Engineers based all around the world.",
    url: "https://www.datadoghq.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "DataStax",
    body: "Consulting based on Apache Cassandra.",
    url: "http://www.datastax.com/company/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Deeson",
    body: "UK-based with European team. Digital agency specialising in Drupal, Symfony and Laravel.",
    url: "https://www.deeson.co.uk/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Demio",
    body: "Webinar platform that just works.",
    url: "https://demio.com/inside/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "digitalminds.io",
    body: "Freelance platform, open for Developers, IT-consultants and Digital Experts.",
    url: "http://digitalminds.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "DigitalOcean",
    body: "Simple Cloud Hosting, Built for Developers.",
    url: "https://www.digitalocean.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Discourse",
    body: "Civilized discussion for your community.",
    url: "https://www.discourse.org/team",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "DNSimple",
    body: "Small 100% remote and globally distributed team working to make domain management an afterthought.",
    url: "https://dnsimple.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Doist",
    body: "Redefining productivity since 2007, 100% Remotely.",
    url: "https://doist.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Dotsub",
    body: "Browser-based platform for subtitling & translating online videos. Java / Spring, JavaScript / React.js.",
    url: "https://dotsub.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Doximity",
    body: "Largest online medical network of US physicians. Ruby, Rails, Go, JavaScript, MySQL.",
    url: "https://www.doximity.com/about/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Drupal Association",
    body: "Non-profit supporting the Drupal project. ",
    url: "https://assoc.drupal.org/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "DuckDuckGo",
    body: "Search engine.",
    url: "https://duck.co/help/company/hiring",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "EasyCommunicationTechnology",
    body: ".NET development using C#, Angular, Azure. Remote-first company.",
    url: "https://www.easycomtec.com/homeoffice/developer",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Elastic",
    body: "Open source search & analytics.",
    url: "https://www.elastic.co/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Envato",
    body: "Maker of ThemeForest and other online marketplaces. MySQL, Ruby, Rails, Javascript. Distributed team with HQ in Melbourne, Australia.",
    url: "https://envato.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Etsy",
    body: "Marketplace for artists. MySQL, Memcache, PHP. Offices in Dublin, Paris, San Francisco, New York, London and Melbourne.",
    url: "https://www.etsy.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Eyeo",
    body: "Maker of AdBlock Plus. Main office in Cologne, Germany.",
    url: "https://eyeo.com/en/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Findify",
    body: "E-commerce search powered by machine learning and big data. Team distributed across Europe.",
    url: "https://findify.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Fog Creek",
    body: "NY-based software company. Makers of bug-tracking and source control tools. Workday must overlap New York afternoons (1700 - 2200 GMT).",
    url: "http://www.fogcreek.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "General Assembly",
    body: "Physical and on-line education for technology, business, and design.",
    url: "https://generalassemb.ly/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Ghost",
    body: "Publishing platform.",
    url: "https://ghost.org/about/#careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Gigster",
    body: "vetted network of top 5% freelancers worldwide. PM, Dev, Sales positions available.",
    url: "https://gigster.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Gitbook",
    body: "Publishing toolchain based on git. Javascript, node.js, Go.",
    url: "http://jobs.gitbook.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "GitHub",
    body: "",
    url: "https://github.com/about/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "GitLab",
    body: "Competitor to GitHub.",
    url: "https://about.gitlab.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "GlueNetworks",
    body: "Network automation company.",
    url: "http://gluenetworks.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Gradle",
    body: "Open Source Build Tool ; Enterprise SaaS and on-premise. Fully remote. Java, Groovy, Kotlin.",
    url: "https://gradle.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "GrooveHQ",
    body: "Help desk software.",
    url: "https://www.groovehq.com/about",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Hanzo",
    body: "Web archiving company. Fully Remote. Python, AWS.",
    url: "https://www.hanzo.co/about-us/careers-uk",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Harvest",
    body: "Time tracking software. ",
    url: "https://www.getharvest.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "HashiCorp",
    body: "Open source tools for automating the modern data center. Go, Ruby, Rails, Ember, JavaScript.",
    url: "https://www.hashicorp.com/jobs.html",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "HE:labs",
    body: "",
    url: "https://helabs.com/us/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Healthfinch",
    body: "Making Healthcare systems more usable. HQ in Madison, WI, USA. Ruby, Javascript.",
    url: "http://www.healthfinch.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Heap",
    body: "Web & Mobile Analytics.",
    url: "https://heapanalytics.com/careers/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Help Scout",
    body: "A help desk for teams that insist on a delightful customer experience.",
    url: "https://www.helpscout.net/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Heroku",
    body: "PaaS Cloud, makes devs' experience awesome, Ruby, Erlang, Javascript, Golang, Python.",
    url: "https://www.heroku.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Honeybadger",
    body: "Ruby. 100% remote.",
    url: "https://www.honeybadger.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Hotjar",
    body: "Analytics & Feedback tool.",
    url: "https://careers.hotjar.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Hubstaff",
    body: "Time tracking solution with multiple integrations.",
    url: "https://hubstaff.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Igalia",
    body: "Open source consultancy. HQ in Spain.",
    url: "https://www.igalia.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Incsub",
    body: "Remote team that builds Wordpress projects.",
    url: "http://incsub.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Inpsyde GmbH",
    body: "WordPress Agency in Germany.",
    url: "https://inpsyde.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Institute for Nonprofit News",
    body: "Nonprofit news organization.",
    url: "https://inn.org/about/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Instructure",
    body: "We make software that makes people smarter.",
    url: "https://www.instructure.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Intellum",
    body: "We build employee collaboration, performance and learning tools. Ruby, iOS, Android, AWS, GCS.",
    url: "http://intellum.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "InVision",
    body: "prototyping, collaboration & workflow platform.",
    url: "https://www.invisionapp.com/company#jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Isos Technology",
    body: "premier Atlassian Platinum & Enterprise Solution Partner, helping organizations solve complex development and business problems with the Atlassian tools.",
    url: "https://careers.isostech.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Jackson River",
    body: "Digital-first technology and strategy for nonprofits.",
    url: "https://www.jacksonriver.com/about/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Judge.me",
    body: "A review platform for ecommerces. Our company is fully remote across 4 continents.",
    url: "http://judge.me/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Keepsafe",
    body: "Mobile-first privacy products, making privacy easy for the world to opt into.",
    url: "https://www.getkeepsafe.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Khan Academy",
    body: "EdTech. Non-profit focusing on K-12 STEM. Less, React, Flux, Backbone, jQuery, Python, Google App Engine, Swift, and Objective-C.",
    url: "https://www.khanacademy.org/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Knack",
    body: "The easy online database.",
    url: "https://www.knack.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "LaterPay",
    body: "The (micro)payment enabler. Munich, Germany. Python, JavaScript, AWS.",
    url: "https://www.laterpay.net/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "LaunchPotato",
    body: "Startup studio based in Delray Beach, Florida.",
    url: "http://launchpotato.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Librato",
    body: "Cloud Monitoring.",
    url: "http://solarwinds.jobs/solarwinds-cloud/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Linaro",
    body: "OpenSource Engineering on ARM.",
    url: "https://www.linaro.org/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Lincoln Loop",
    body: "WebDev shop.",
    url: "https://lincolnloop.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Litmus",
    body: "Optimization tools for email professionals. Offices in Boston and London, but nearly 50% of the team works remotely.",
    url: "https://litmus.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "LivingSocial",
    body: "Company-wide support for teams of experienced, remote developers. Lots of autonomy.",
    url: "https://jobs.groupon.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Lullabot",
    body: "Strategy, design and development using Drupal.",
    url: "https://www.lullabot.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "madewithlove",
    body: "We help companies build digital products and bring new juice to teams that seem to jam.",
    url: "https://madewithlove.be/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Maintainer Mountaineer",
    body: "Open source community management as a service.",
    url: "https://maintainer.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MariaDB",
    body: "Open source database.",
    url: "https://mariadb.com/about-us/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MarsBased",
    body: "MarsBased is a development consultancy from Barcelona offering end‑to‑end web & mobile apps based on Ruby on Rails, Angular and other Javascript frameworks.",
    url: "https://marsbased.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mapbox",
    body: "Map integration tools for various platforms.",
    url: "https://www.mapbox.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MCFTech",
    body: "Applications to help you run your business succesfully.",
    url: "https://www.mcftech.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MeetEdgar",
    body: "Automated social sharing. US remote.",
    url: "https://meetedgar.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mobile Jazz",
    body: "We are a dedicated team of highly-skilled engineers, designers and marketing experts on a mission to build a more beautiful digital world. We are a remote friendly company with headquarters in Barcelona.",
    url: "https://mobilejazz.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Modern Tribe",
    body: "A digital agency with a modern twist. All freelancers. All experts.",
    url: "http://tri.be/about/join-our-team/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Modus Create",
    body: "Modus is a digital design-build agency driven by world-class talent. PHP, Javascript.",
    url: "https://moduscreate.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mosalingua",
    body: "Learn words, enjoy the world.",
    url: "https://www.mosalingua.com/en/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "MVP Space",
    body: "Test a business idea with your target audience or show its potential to your investors.",
    url: "http://mvp-space.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Mozilla",
    body: "Firefox has a 'Remote' option under it's location searchbar.",
    url: "https://careers.mozilla.org/listings/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "NearForm",
    body: "NearForm evolves enterprises by building high-performance, open software. Our global team uses modern processes and tools to help clients innovate at speed.",
    url: "https://www.nearform.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Nectafy",
    body: "nbound marketing and content creation.",
    url: "http://nectafy.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Netsparker",
    body: "Web Application Security Scanner.",
    url: "https://www.netsparker.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Next Big Sound",
    body: "Analytics and Insights for the Music Industry.",
    url: "https://www.nextbigsound.com/about",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "NinjaCat",
    body: "Reporting, Monitoring & Call Tracking Platform for Leading Digital Agencies.",
    url: "https://www.ninjacat.io/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Niteo",
    body: "A decade old SaaS studio full of bright ideas, building smart solutions to empower small businesses online.",
    url: "https://niteo.co/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "NodeSource",
    body: "NodeSource is dedicated to creating a sustainable ecosystem for Node.js.",
    url: "https://nodesource.com/about",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ofri",
    body: "A swiss online marketplace that connects homeowners with quality home improvement professionals.",
    url: "https://www.ofri.ch/job_openings",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Olark",
    body: "Chat support funnel.",
    url: "https://www.olark.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "onTheGo Systems",
    body: "WordPress Developer, Supporter and Marketing Jobs.",
    url: "https://www.onthegosystems.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Onyo",
    body: "Transforming the eating out experience in pure pleasure.",
    url: "http://www.onyo.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "OpenCraft",
    body: "Open edX development (Free Software MOOC project).",
    url: "http://opencraft.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Owsy",
    body: "International studio focused on creating products for financial service firms.",
    url: "http://owsy.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Parknav",
    body: "Intelligent parking using AI.",
    url: "https://parknav.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Parsely",
    body: "Analytics solutions.",
    url: "http://www.parsely.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Particular Software (NServiceBus)",
    body: "Enterprise Service Bus, Messaging, C#, Open Source.",
    url: "https://particular.net/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Patients Know Best",
    body: "Empowering patients to manage their care, enabling professionals to share information while improving efficiencies for payers.",
    url: "https://patients.workable.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Paylocity",
    body: "HR and payroll solutions.",
    url: "http://www.paylocity.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Pilot",
    body: "Pilot is a software platform that removes all the pain from contract work. We find work, negotiate contracts, send invoices and chase payments for hundreds of forward-looking engineers and designers around the world.",
    url: "https://pilot.co/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Pleo",
    body: "Pleo is a company payment card solution that automates expense reports and simplifies company spending.",
    url: "https://careers.pleo.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Precision Nutrition",
    body: "Online Nutrition Coaching and Certification.",
    url: "http://www.precisionnutrition.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "PreviousNext",
    body: "Australian based Drupal agency.",
    url: "https://www.previousnext.com.au/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Prezly",
    body: "SaaS PR platform. PHP, React, JS, Postgres. 100% remote.",
    url: "https://www.prezly.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "RainforestQA",
    body: " On demand QA as a service.",
    url: "https://www.rainforestqa.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Reaction Commerce",
    body: "Fastest-growing open source ecommerce platform. Node.js, MongoDB, Kubernetes, Docker.",
    url: "https://reactioncommerce.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Real HQ",
    body: "Maker of Agent Pronto, software designed to help make home buying and selling a better experience. We've been remote since the start, now 50+ spread across the globe. Ruby, Rails, React.js, iOS/Android.",
    url: "https://realhq.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "RebelMouse",
    body: "Social publishing platform. Python, JS & iOS/Android developers. All over the world team.",
    url: "https://blog.rebelmouse.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Recurly",
    body: "recurring billing management for subscription-based businesses.",
    url: "https://recurly.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Red Hat.",
    body: "",
    url: "http://jobs.redhat.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "RightScale.",
    body: "",
    url: "http://www.rightscale.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Sangoma",
    body: "Trusted leader in delivering globally scalable Voice-Over-IP telephony systems, both on-site and cloud-based. C, PHP, Python, JavaScript, Linux, FreePBX, VoIP.",
    url: "http://www.sangoma.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Scrapinghub",
    body: "",
    url: "https://scrapinghub.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ServiceNow",
    body: "Enterprise cloud computing to improve service levels, energize employees, and change the way your enterprise works. Work at lightspeed.",
    url: "http://jobs.jobvite.com/servicenow/search?c=&l=&r=&t=&q=remote",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ShakaCode",
    body: "A global web development software consultancy and product company.",
    url: "http://www.shakacode.com/about/index.html#work-with-us",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Shogun",
    body: "Build and optimize eCommerce landing pages. Ruby / Rails, Go, JavaScript, React. 100% remote.",
    url: "https://getshogun.com/team",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Signal",
    body: "These people make the fantastic Signal app. US Only.",
    url: "https://www.signal.org/workworkwork/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Simple",
    body: "",
    url: "https://www.simple.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Skyscrapers",
    body: "Cloud hosting services & management. Working with multiple cloud providers (AWS, Digital Ocean, Linode, ...). 100% remote.",
    url: "http://skyscrapers.eu/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "SoftwareMill",
    body: "",
    url: "https://softwaremill.com/join-us/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Soshace",
    body: "Angular/React/Vue.js/Java/Python remote development company. ",
    url: "https://soshace.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Songspace",
    body: "Helps music creators collaborate, catalog, and share work with their professional team.",
    url: "https://songspace.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Soostone",
    body: "",
    url: "http://www.soostone.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Splice Machine",
    body: "Combines the functionality of a relational database, data warehouse, and machine learning in one unified AI platform.",
    url: "https://www.splicemachine.com/company/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Spreaker",
    body: "Discover and listen to your favorite podcasts.",
    url: "https://www.spreaker.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "StackExchange.",
    body: "",
    url: "http://stackexchange.com/work-here",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Strongloop",
    body: "",
    url: "https://strongloop.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Student Loan Hero",
    body: "100% remote company on a mission to help 44 million Americans manage and repay over $1.4 trillion in student loan.",
    url: "https://studentloanhero.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "StyleSeat",
    body: "we love high-impact remote engineers, collaboration, creativity, python, angularjs.",
    url: "http://static.styleseat.com/jobs/index.html",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Surevine",
    body: "",
    url: "https://www.surevine.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Surge",
    body: "100% remote consulting company working primarily in Node.JS, iOS, .NET, PHP, and Android.",
    url: "http://www.surgeforward.com/careers/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Sysdig Cloud",
    body: "",
    url: "https://sysdig.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Taskade",
    body: "Remote team building real-time collaboration & collaborative editing for teams.",
    url: "https://www.taskade.com/contact/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "TaxJar",
    body: "Eliminate sales tax headaches.",
    url: "https://www.taxjar.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Teamed.io",
    body: "",
    url: "http://teamed.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "TeamSnap",
    body: "TeamSnap is the No. 1 online sports team management software. 80% remote employees.",
    url: "https://www.teamsnap.com/about/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "TED ",
    body: "Technology team supports ted.com and internal tools. All engineers are remote. Ruby on Rails, JavaScript, Ember.js.",
    url: "http://www.ted.com/about/our-organization/jobs-at-ted",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Teleport. ",
    body: "",
    url: "https://teleport.org/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Tesera",
    body: "We disrupt conventional thinking to expand what is possible. We ignite change in the future we share.",
    url: "https://tesera.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "The Grid",
    body: "AI website builder. 100% distributed team.",
    url: "http://thegrid.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Thermeon",
    body: "Car rental software - 100% remote technical team.",
    url: "http://thermeon.com/jobs.html",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "TimeDoctor",
    body: "Time tracking with screenshots, web and app usage monitoring, and integrations.",
    url: "https://www.timedoctor.com/about-us.html",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Tipe",
    body: "Next Generation API-first CMS with GraphQL or REST API. Built with Nuxt.js, Serverless, AWS. 25% remote.",
    url: "https://tipe.io/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Toggl",
    body: "",
    url: "https://jobs.toggl.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Toptal",
    body: "100% remote development company, solving worldwide talent shortage.",
    url: "https://www.toptal.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Tortuga Backpacks",
    body: "Backpacks for city travel.",
    url: "https://www.tortugabackpacks.com/pages/join",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Transloadit",
    body: "The world's most versatile file uploading & encoding service, since 2009, by devs for devs.",
    url: "https://transloadit.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Trello",
    body: "",
    url: "https://trello.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Twin Technologies.",
    body: "",
    url: "http://twintechs.com/about-twin/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Vidalingua",
    body: "Bringing language apps to life.",
    url: "http://www.vidalingua.com/amaze.php",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "WAAT",
    body: "A cross-functional digital agency that adapts to project needs.",
    url: "https://waat.eu/job/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Walltime",
    body: "A Brazilian digital assets exchange and other products & services using Blockchain technology.",
    url: "https://walltime.info/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Water Lily Pond",
    body: "Advertising and marketing communication services.",
    url: "http://waterlilypond.co.uk/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "wemake.services",
    body: "We sell repeatable software development process. Fully remote. Python, Javascript, Vue.",
    url: "https://wemake.services/meta/employees",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Wikimedia",
    body: "",
    url: "https://wikimediafoundation.org/wiki/Work_with_us",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "X-Team",
    body: "Work on incredible web and mobile projects, with extraordinary developers. Unleash your potential. From anywhere. We are X-Team.",
    url: "https://x-team.com/join/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "You Need a Budget",
    body: "Bank syncing and goals and debt management.",
    url: "https://www.youneedabudget.com/jobs/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "YourSports",
    body: "A social network for your favorite teams.",
    url: "https://www.yoursports.com/jobs",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Zamphyr",
    body: "School 2.0 for learning computer science. Remote-first, 100% JavaScript mostly Meteor.",
    url: "https://zamphyr.com/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "Zapier",
    body: "",
    url: "https://zapier.com/about/",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
  {
    name: "ZipRecruiter",
    body: "Perl/Catalyst shop that has some of the best Perl devs working remotely.",
    url: "https://www.ziprecruiter.com/careers",
    hq: null,
    remoteModel: null,
    timezone: null,
  },
];

export default remoteCompanies;
